---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Сайт должен иметь мобильную версию.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен быть способен выдерживать большое количество одновременно оформленных заказов
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность изменять количество товара в корзине
  - Стоимость товаров на сайте в русской версии олжна быть в рублях
  - Фильтр по товарам не должен сбрасываться при возвращении обратно с карточки товара
  - 
